---
- name: Ensure Dashy Docker container is running
  community.docker.docker_container:
    name: dashy
    image: tychobrouwer/dashy-tychobrouwer
    state: started
    ports:
      - "1080:80"
    networks:
      - name: web-secure
    volumes:
      - /root/dashy-conf.yaml:/app/public/conf.yml
    restart_policy: unless-stopped
    cpus: "{{ portainer_cpus }}"
