---
- name: Ensure Dashy Docker container is running
  community.docker.docker_container:
    name: dashy
    image: tychobrouwer/dashy-tychobrouwer
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.routers.dashy.rule: Host(`dash.{{ portainer_root_domain }}`)
    #   traefik.http.routers.dashy.entrypoints: web-secure
    #   traefik.http.routers.dashy.tls: "true"
    state: started
    ports:
      - "1080:80"
    networks:
      - name: web-secure
    volumes:
      - /root/dashy-conf.yaml:/app/public/conf.yml
    restart_policy: unless-stopped
    cpus: "{{ portainer_cpus }}"
