---
- name: Ensure docker GPG signing key is installed
  ansible.builtin.apt_key:
    url: "{{ portainer_docker_ce_deb_gpg }}"
    state: present

- name: Ensure docker repository is added
  ansible.builtin.apt_repository:
    repo: "{{ portainer_docker_ce_deb_repo }}"
    state: present

- name: Ensure docker tools are installed
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
