---
- name: Ensure Grafana Docker volume is present
  community.docker.docker_volume:
    name: grafana_data

- name: Ensure Grafana configuration file is present
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /root/grafana.ini
    mode: "0644"
    owner: root
    group: root

- name: Ensure Grafana Docker container is running
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    networks:
      - name: web-secure
    volumes:
      - /root/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    restart_policy: unless-stopped
    cpus: "{{ portainer_cpus }}"
