---
# tasks file for ansible-portainer
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Ensure authelia-config exists
  ansible.builtin.file:
    path: /root/authelia-config
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: authelia_enabled

- name: Ensure templates are deployed on remote
  ansible.builtin.template:
    src: "{{ portainer_authelia_config_template }}"
    dest: /root/authelia-config/configuration.yaml
    mode: "0644"
    owner: root
    group: root
  when: authelia_enabled

- name: Ensure templates are deployed on remote
  ansible.builtin.template:
    src: "{{ portainer_dashy_config_template }}"
    dest: /root/dashy-conf.yaml
    mode: "0644"
    owner: root
    group: root
  when: dashy_enabled

- name: Ensure templates are deployed on remote
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - { src: "{{ portainer_traefik_dynamic_template }}", dest: /root/traefik-dynamic.yaml }
    - { src: "{{ portainer_traefik_static_template }}", dest: /root/traefik-static.yaml }
  when: traefik_enabled
  notify: restart traefik

- name: Install Docker
  ansible.builtin.include_tasks: docker.yml

- name: Install Authelia container
  ansible.builtin.include_tasks: authelia.yml
  when: authelia_enabled

- name: Install Portainer container
  ansible.builtin.include_tasks: portainer.yml
  when: portainer_enabled

- name: Install Traefik container
  ansible.builtin.include_tasks: traefik.yml
  when: traefik_enabled

- name: Install Dashy container
  ansible.builtin.include_tasks: dashy.yml
  when: dashy_enabled

- name: Install Cloudflare DDNS container
  ansible.builtin.include_tasks: cloudflare-ddns.yml
  when: cloudflare_ddns_enabled

- name: Install InfluxDB container
  ansible.builtin.include_tasks: influxdb.yml
  when: influxdb_enabled

- name: Install Grafana container
  ansible.builtin.include_tasks: grafana.yml
  when: grafana_enabled

- name: Install Passbolt container
  ansible.builtin.include_tasks: passbolt.yml
  when: passbolt_enabled

- name: Install Watchtower container
  ansible.builtin.include_tasks: watchtower.yml
  when: watchtower_enabled

- name: Install Tandoor container
  ansible.builtin.include_tasks: tandoor.yml
  when: tandoor_enabled
