---
- name: Ensure Tandoor database Docker volume is present
  community.docker.docker_volume:
    name: database_volume_postgres

- name: Ensure Tandoor database container is running
  community.docker.docker_container:
    name: postgres-tandoor
    image: postgres:16-alpine
    labels:
      watchtower.enable: "false"
    env:
      POSTGRES_USER: djangodb
      POSTGRES_PASSWORD: "{{ portainer_tandoor.postgres_password }}"
      POSTGRES_DB: djangodb
    volumes:
      - database_volume_postgres:/var/lib/postgresql/data
    restart_policy: unless-stopped
    ports:
      - 5432:5432

- name: Ensure Tandoor static volume is present
  community.docker.docker_volume:
    name: tandoor_static

- name: Ensure Tandoor media volume is present
  community.docker.docker_volume:
    name: tandoor_media

- name: Ensure Tandoor Docker container is running
  community.docker.docker_container:
    name: tandoor
    image: vabene1111/recipes
    state: started
    ports:
      - 9080:8080
    env:
      SECRET_KEY: "{{ portainer_tandoor.secret_key }}"
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: djangodb
      POSTGRES_PASSWORD: "{{ portainer_tandoor.postgres_password }}"
      POSTGRES_DB: djangodb
    restart_policy: unless-stopped
    networks:
      - name: web-secure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tandoor_static:/opt/recipes/staticfiles
      - tandoor_media:/opt/recipes/mediafiles
    cpus: "{{ portainer_cpus }}"
