---
- name: Ensure traefik static config is on remote
  ansible.builtin.template:
    src: traefik-static.yaml.j2
    dest: /root/traefik-static.yaml
    mode: "0600"
    owner: root
    group: root

- name: Ensure additional certificates are on remote
  ansible.builtin.copy:
    dest: /root/{{ item.file }}
    content: "{{ item.cert }}"
    mode: "0600"
    owner: root
    group: root
  with_items: "{{ portainer_traefik_additional_certs }}"

- name: Ensure web network for Traefik is present
  community.docker.docker_network:
    name: web-secure
    internal: false
    state: present

- name: Ensure Traefik reverse proxy Docker container is running
  community.docker.docker_container:
    name: traefik
    image: traefik:latest
    state: started
    command:
      - --configFile=/etc/traefik/static.yaml
    ports:
      - 443:443
      - 8080:8080
    restart_policy: unless-stopped
    networks:
      - name: web-secure
    volumes: "{{ portainer_traefik_default_volumes + portainer_traefik_additional_volumes }}"
