---
- name: Ensure Watchtower Docker container is running
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_CLEANUP: "true"
    restart_policy: unless-stopped
    cpus: "{{ portainer_cpus }}"
